[tool.black]
line-length = 88

[tool.ruff]
line-length = 88
lint.select = ["E", "F", "W", "I", "B"]
lint.ignore = ["E501"]

[tool.pytest.ini_options]
pythonpath = "."
addopts = "-v --cov=. --cov-report=term"